### PR TITLE
Update README.md with RELEASE_COOKIE

### PR DESCRIPTION
**Pull request by noozo**
Adding reminder to set RELEASE_COOKIE

### CODE REVIEW

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by chrismccord** [comment]
This is not strictly true and would only be required if (like on our convo in slack) you have separate apps trying to connect to eachother. By default, the cookies should match just fine across the same app within a release.

**Comment by noozo** [comment]
@chrismccord what do you mean by separate apps? i have one single fly.io app running with scale = 2 and those two instances don't talk to each other (haven't tried the other fully qualified hint you gave me yet).

**Comment by noozo** [comment]
oh, you mean the cookie itself isn't required, only that they have fully qualified names?

**Pull request merged**
